apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: {{ template "splunk-kubernetes-metrics.fullname" . }}
  labels:
    app: {{ template "splunk-kubernetes-metrics.name" . }}
    chart: {{ template "splunk-kubernetes-metrics.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    k8s-app: heapster-fluentd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "splunk-kubernetes-metrics.name" . }}
      release: {{ .Release.Name }}
      k8s-app: heapster
  template:
    metadata:
      labels:
        app: {{ template "splunk-kubernetes-metrics.name" . }}
        release: {{ .Release.Name }}
        k8s-app: heapster
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ''
        checksum/config: {{ include (print $.Template.BasePath "/configMap.yaml") . | sha256sum }}
    spec:
      serviceAccountName: {{ template "splunk-kubernetes-metrics.serviceAccountName" . }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
      {{- end }}
      containers:
        - image: k8s.gcr.io/heapster-amd64:{{ .Values.image.heapsterTag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          name: splunk-heapster
          command:
            - /heapster
            # - --source=kubernetes.summary_api:''
            - --source=kubernetes
            - --sink=statsd:udp://127.0.0.1:9001
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8082
              scheme: HTTP
            initialDelaySeconds: 180
            timeoutSeconds: 5
          resources:
{{ toYaml .Values.resources.heapster | indent 12 }}
        - image: gimil/k8s-l:{{ .Values.image.sidecarTag }}
          name: splunk-fluentd-heapster
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - -c
            - /fluentd/etc/fluent.conf
          env:
            - name: MY_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: SPLUNK_HEC_HOST
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: SPLUNK_HEC_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ template "splunk-kubernetes-metrics.fullname" . }}
                  key: splunk_hec_token
          resources:
{{ toYaml .Values.resources.sidecar | indent 12 }}
          volumeMounts:
          - name: conf-configmap
            mountPath: /fluentd/etc
          - name: secrets
            mountPath: /fluentd/etc/splunk
            readOnly: true
      volumes:
      - name: conf-configmap
        configMap:
          name: {{ template "splunk-kubernetes-metrics.fullname" . }}
      - name: secrets
        secret:
          secretName: {{ template "splunk-kubernetes-metrics.fullname" . }}
