# This role allows read access to the kubelet summary API
{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubelet-summary-api-read
  labels:
    app: {{ template "splunk-kubernetes-metrics.name" . }}
    chart: {{ template "splunk-kubernetes-metrics.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
rules:
{{- if .Values.podSecurityPolicy.create }}
- apiGroups:      [{{ .Values.podSecurityPolicy.apiGroup | quote }}]
  resources:      ['podsecuritypolicies']
  verbs:          ['use']
  resourceNames:  [{{ template "splunk-kubernetes-metrics.fullname" . }}]
{{- end }}
- apiGroups:
  - ""
  resources:
  - "nodes"
  - "nodes/stats"
  - "nodes/metrics"
  verbs:
  - "get"
{{- end }}
