{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ template "splunk-kubernetes-metrics.fullname" . }}-aggregator
  labels:
    app: {{ template "splunk-kubernetes-metrics.name" . }}
    chart: {{ template "splunk-kubernetes-metrics.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: "kube-api-aggregator"
subjects:
- kind: ServiceAccount
  name: {{ template "splunk-kubernetes-metrics.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}
