dependencies:
  - name: splunk-kubernetes-logging
    version: 1.5.3
    repository: https://splunk.github.io/splunk-connect-for-kubernetes/
    condition: splunk-kubernetes-logging.enabled
  - name: splunk-kubernetes-objects
    version: 1.5.3
    repository: https://splunk.github.io/splunk-connect-for-kubernetes/
    condition: splunk-kubernetes-objects.enabled
  - name: splunk-kubernetes-metrics
    version: 1.5.3
    repository: https://splunk.github.io/splunk-connect-for-kubernetes/
    condition: splunk-kubernetes-metrics.enabled
