apiVersion: v1
version: 1.0.0
name: splunk-kubernetes-logging
description: Collect logs with Splunk.
home: https://github.com/splunk/splunk-connect-for-kubernetes
sources:
  - https://github.com/splunk/splunk-connect-for-kubernetes/tree/master/helm-chart/charts/splunk-kubernetes-logging
keywords:
  - splunk
  - monitoring
  - logging
maintainers:
  - name: Gimi Liang
