apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: {{ template "splunk-kubernetes-logging.fullname" . }}
  labels:
    app: {{ template "splunk-kubernetes-logging.name" . }}
    chart: {{ template "splunk-kubernetes-logging.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    engine: fluentd
spec:
  template:
    metadata:
      labels:
        app: {{ template "splunk-kubernetes-logging.name" . }}
        release: {{ .Release.Name }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configMap.yaml") . | sha256sum }}
    spec:
      {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
      {{- end }}
      containers:
      - name: splunk-fluentd-k8s-logs
        image: {{ .Values.image.name }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        args:
          - -c
          - /fluentd/etc/fluent.conf
        env:
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: MY_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: MY_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: SPLUNK_HEC_TOKEN
            valueFrom:
              secretKeyRef:
                name: {{ template "splunk-kubernetes-logging.secret" . }}
                key: splunk_hec_token
        resources:
{{ toYaml .Values.resources | indent 10 }}
        volumeMounts:
        - name: varlog
          mountPath: /var/log
        - name: varlibdockercontainers
          mountPath: {{ with .Values.dockerPath }}{{ printf "%s/containers" . | quote }}{{ end }}
          readOnly: true
        - name: journallogpath
          mountPath: {{ .Values.journalLogPath | quote }}
          readOnly: true
        - name: conf-configmap
          mountPath: /fluentd/etc
        - name: secrets
          mountPath: /fluentd/etc/splunk
          readOnly: true
      terminationGracePeriodSeconds: 30
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: {{ with .Values.dockerPath }}{{ printf "%s/containers" . | quote }}{{ end }}
      - name: journallogpath
        hostPath:
          path: {{ .Values.journalLogPath | quote }}
      - name: conf-configmap
        configMap:
          name: {{ template "splunk-kubernetes-logging.fullname" . }}
      - name: secrets
        secret:
          secretName: {{ template "splunk-kubernetes-logging.secret" . }}
