apiVersion: v1
version: 1.1.0
name: splunk-kubernetes-objects
description: Collect Kubernetes objects with Splunk.
home: https://github.com/splunk/splunk-connect-for-kubernetes/tree/master/helm-chart/charts/splunk-kubernetes-objects
sources:
  - https://github.com/splunk/splunk-connect-for-kubernetes/tree/master/helm-chart/charts/splunk-kubernetes-objects
  - https://github.com/splunk/fluent-plugin-splunk-hec
  - https://github.com/splunk/fluent-plugin-kubernetes-objects
keywords:
  - splunk
  - monitoring
  - objects
  - metadata
maintainers:
  - name: Splunk Inc.
    email: DataEdge@splunk.com
